### ISSUE TITLE
Dataset availability

### ISSUE THREAD

**Issue by msknorr** [sonhamin/dermtools#3]
Dear authors, 

thank you for the interesting paper!
Could you provde information about how to apply for access to the annotated dataset (100 dermnet images)?

Kind regards

**Comment by sonhamin** [comment]
Thanks for your interest in our paper!

There are two options:

1. You could write a simple python script to crawl all the images from [this site](https://dermnetnz.org/image-library) (you would have to clean the data by going through to eliminate any unwanted images). 
2. You could download a clean dataset from somewhere like [kaggle](https://www.kaggle.com/datasets/shubhamgoel27/dermnet). Though easier, you would be limited to what data they have available.

**Comment by msknorr** [comment]
Hello, thanks for you reply. 

I already downloaded the dermnet NZ images. 
But according to your paper you have annotated 100 of these images by hand:
"the erythema of 100 images was masked by dermatologists"
Would it be possible to get these masks?

Thank you!

**Comment by sonhamin** [comment]
Could you shoot me a email at sonhamin3@gmail.com ?
